[workspace]
channels = ["robostack-jazzy", "conda-forge"]
name = "create3_ws"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=58.2.0"
ros-jazzy-ros-gz = ">=1.0.7,<2"
ros-jazzy-joint-state-publisher = ">=2.4.0,<3"
ros-jazzy-ros-gz-bridge = ">=1.0.7,<2"
ros-jazzy-ros-gz-sim = ">=1.0.7,<2"
ros-jazzy-ros-gz-image = ">=1.0.7,<2"
ros-jazzy-ros-gz-interfaces = ">=1.0.7,<2"
ros-jazzy-control-msgs = ">=5.8.0,<6"
